services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app_transit_db
      POSTGRES_USER: transit_app_user
      POSTGRES_PASSWORD: transit_app_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
