package com.transit.platform.dossier.enums;

public enum EvenementHistorique {
    DOSSIER_CREATED, DOSSIER_UPDATED, STATUS_CHANGED, RESPONSABLE_CHANGED,
    MARCHANDISE_ADDED, DOCUMENT_ADDED, COTATION_CREATED, FACTURE_CREATED,
    PAIEMENT_RECEIVED, CHARGE_CREATED, VALIDATION_REQUESTED, DOSSIER_CLOSED
}
